from __future__ import annotations

import html

from .commands import render_powershell
from .models import ExportRequest


def _markdown(request: ExportRequest) -> str:
    report = request.report
    lines = [
        f"# {report.fixture_name}",
        "",
        f"**Verdict:** {report.verdict.value}",
        f"**Recommendation:** {report.recommendation_id or 'none'}",
        "",
        report.summary,
        "",
        "| Candidate | Verdict | Coverage | Delta | Evidence |",
        "|---|---:|---:|---:|---|",
    ]
    for candidate in report.candidates:
        coverage = f"{candidate.coverage * 100:.1f}%" if candidate.coverage is not None else "-"
        delta = f"{candidate.delta_percent:+.1f}%" if candidate.delta_percent is not None else "-"
        lines.append(f"| {candidate.label} | {candidate.verdict.value} | {coverage} | {delta} | {candidate.evidence.value} |")
    lines.extend(["", "Generated by MoE Autopilot Studio. Calculations are deterministic."])
    return "\n".join(lines) + "\n"


def export_report(request: ExportRequest) -> tuple[str, str]:
    if request.format == "json":
        return "application/json", request.report.model_dump_json(indent=2)
    if request.format == "markdown":
        return "text/markdown", _markdown(request)
    if request.format == "powershell":
        if request.run_spec is None:
            raise ValueError("PowerShell export requires a run_spec")
        blocks = [f"# {request.run_spec.label}", "$ErrorActionPreference = 'Stop'"]
        for index, command in enumerate(request.run_spec.commands, start=1):
            blocks.extend(["", f"# Step {index}", render_powershell(command)])
        return "text/plain", "\n".join(blocks) + "\n"
    markdown = _markdown(request)
    body = f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>{html.escape(request.report.fixture_name)}</title>
<style>body{{font:16px system-ui;max-width:920px;margin:40px auto;padding:0 24px;color:#17211b}}pre{{white-space:pre-wrap;background:#f2f5f3;padding:24px;border:1px solid #ccd5cf;border-radius:6px}}</style>
</head><body><pre>{html.escape(markdown)}</pre></body></html>"""
    return "text/html", body
